packages:
  - .

# Allow these dependencies to run native build scripts during install.
# (pnpm v10+ may require explicit allow-listing)
onlyBuiltDependencies:
  - sharp

ignoredBuiltDependencies:
  - unrs-resolver
