// Comprehensive, bilingual business category taxonomy for seeding.
// NOTE: Arabic is stored in the existing system as "ar".

export const CATEGORY_TAXONOMY = [
  {
    slug: "food-beverage",
    iconId: "restaurant",
    name: { en: "Food & Beverage", ar: "الأطعمة والمشروبات" },
    children: [
      { slug: "restaurants", iconId: "restaurant", name: { en: "Restaurants", ar: "مطاعم" } },
      { slug: "cafes", iconId: "cafe", name: { en: "Cafes", ar: "مقاهي" } },
      { slug: "bakeries", iconId: "restaurant", name: { en: "Bakeries", ar: "مخابز" } },
      { slug: "desserts", iconId: "gift", name: { en: "Desserts & Sweets", ar: "حلويات" } },
      { slug: "catering", iconId: "delivery", name: { en: "Catering", ar: "تموين" } },
      { slug: "food-delivery", iconId: "delivery", name: { en: "Food Delivery", ar: "توصيل طعام" } },
      { slug: "grocers-specialty", iconId: "grocery", name: { en: "Specialty Grocers", ar: "بقالات متخصصة" } },
      { slug: "butchers", iconId: "grocery", name: { en: "Butchers", ar: "ملحمة" } },
      { slug: "juice-smoothies", iconId: "cafe", name: { en: "Juice & Smoothies", ar: "عصائر وسموذي" } },
      { slug: "tea-shops", iconId: "cafe", name: { en: "Tea Shops", ar: "محلات شاي" } },
    ],
  },
  {
    slug: "retail-shopping",
    iconId: "shopping",
    name: { en: "Retail & Shopping", ar: "البيع بالتجزئة والتسوق" },
    children: [
      { slug: "supermarkets", iconId: "grocery", name: { en: "Supermarkets", ar: "سوبرماركت" } },
      { slug: "convenience-stores", iconId: "grocery", name: { en: "Convenience Stores", ar: "متاجر صغيرة" } },
      { slug: "fashion-clothing", iconId: "fashion", name: { en: "Clothing & Fashion", ar: "ملابس وموضة" } },
      { slug: "shoes-accessories", iconId: "fashion", name: { en: "Shoes & Accessories", ar: "أحذية وإكسسوارات" } },
      { slug: "electronics-stores", iconId: "electronics", name: { en: "Electronics Stores", ar: "محلات إلكترونيات" } },
      { slug: "mobile-shops", iconId: "phone", name: { en: "Mobile Phones", ar: "هواتف محمولة" } },
      { slug: "computers", iconId: "it", name: { en: "Computers & Laptops", ar: "حاسبات محمولة" } },
      { slug: "home-furniture", iconId: "furniture", name: { en: "Home & Furniture", ar: "منزل وأثاث" } },
      { slug: "books-stationery", iconId: "books", name: { en: "Books & Stationery", ar: "كتب وقرطاسية" } },
      { slug: "gifts-florists", iconId: "gift", name: { en: "Gifts & Florists", ar: "هدايا وزهور" } },
      { slug: "jewelry", iconId: "gift", name: { en: "Jewelry", ar: "مجوهرات" } },
      { slug: "sports-outdoor-retail", iconId: "fitness", name: { en: "Sports & Outdoor", ar: "رياضة وخارجية" } },
    ],
  },
  {
    slug: "health-medical",
    iconId: "healthcare",
    name: { en: "Health & Medical", ar: "الصحة والطب" },
    children: [
      { slug: "hospitals", iconId: "healthcare", name: { en: "Hospitals", ar: "مستشفيات" } },
      { slug: "clinics", iconId: "healthcare", name: { en: "Clinics", ar: "عيادات" } },
      { slug: "dental", iconId: "healthcare", name: { en: "Dental", ar: "أسنان" } },
      { slug: "pharmacies", iconId: "pharmacy", name: { en: "Pharmacies", ar: "صيدليات" } },
      { slug: "labs-diagnostics", iconId: "healthcare", name: { en: "Labs & Diagnostics", ar: "مختبرات وتشخيص" } },
      { slug: "physiotherapy", iconId: "fitness", name: { en: "Physiotherapy", ar: "علاج طبيعي" } },
      { slug: "optical", iconId: "healthcare", name: { en: "Optical", ar: "نظارات وبصريات" } },
      { slug: "home-healthcare", iconId: "healthcare", name: { en: "Home Healthcare", ar: "رعاية منزلية" } },
    ],
  },
  {
    slug: "beauty-wellness",
    iconId: "beauty",
    name: { en: "Beauty & Wellness", ar: "التجميل والعناية" },
    children: [
      { slug: "salons", iconId: "beauty", name: { en: "Hair Salons", ar: "صالونات شعر" } },
      { slug: "barbers", iconId: "beauty", name: { en: "Barbers", ar: "حلاقة رجالية" } },
      { slug: "spas", iconId: "beauty", name: { en: "Spas", ar: "منتجعات صحية" } },
      { slug: "nails", iconId: "beauty", name: { en: "Nails", ar: "أظافر" } },
      { slug: "makeup", iconId: "beauty", name: { en: "Makeup", ar: "مكياج" } },
      { slug: "perfumes", iconId: "gift", name: { en: "Perfumes", ar: "عطور" } },
      { slug: "gym-fitness", iconId: "fitness", name: { en: "Gyms & Fitness", ar: "نوادي ولياقة" } },
      { slug: "yoga", iconId: "fitness", name: { en: "Yoga & Pilates", ar: "يوغا وبيلاتس" } },
    ],
  },
  {
    slug: "education-training",
    iconId: "education",
    name: { en: "Education & Training", ar: "التعليم والتدريب" },
    children: [
      { slug: "schools", iconId: "education", name: { en: "Schools", ar: "مدارس" } },
      { slug: "universities", iconId: "education", name: { en: "Universities", ar: "جامعات" } },
      { slug: "training-centers", iconId: "education", name: { en: "Training Centers", ar: "مراكز تدريب" } },
      { slug: "language-centers", iconId: "education", name: { en: "Language Centers", ar: "مراكز لغات" } },
      { slug: "tutoring", iconId: "education", name: { en: "Tutoring", ar: "دروس خصوصية" } },
      { slug: "driving-schools", iconId: "auto", name: { en: "Driving Schools", ar: "مدارس قيادة" } },
    ],
  },
  {
    slug: "professional-services",
    iconId: "professional",
    name: { en: "Professional Services", ar: "الخدمات المهنية" },
    children: [
      { slug: "legal-services", iconId: "legal", name: { en: "Legal Services", ar: "خدمات قانونية" } },
      { slug: "accounting", iconId: "finance", name: { en: "Accounting & Tax", ar: "محاسبة وضرائب" } },
      { slug: "consulting", iconId: "professional", name: { en: "Consulting", ar: "استشارات" } },
      { slug: "hr-recruitment", iconId: "users", name: { en: "HR & Recruitment", ar: "موارد بشرية وتوظيف" } },
      { slug: "translation", iconId: "feather", name: { en: "Translation", ar: "ترجمة" } },
      { slug: "printing-services", iconId: "printing", name: { en: "Printing & Copy", ar: "طباعة ونسخ" } },
      { slug: "security-services", iconId: "security", name: { en: "Security Services", ar: "خدمات أمن" } },
    ],
  },
  {
    slug: "technology-it",
    iconId: "it",
    name: { en: "Technology & IT", ar: "التقنية وتقنية المعلومات" },
    children: [
      { slug: "software-development", iconId: "it", name: { en: "Software Development", ar: "تطوير برمجيات" } },
      { slug: "web-design", iconId: "art", name: { en: "Web Design", ar: "تصميم مواقع" } },
      { slug: "it-support", iconId: "it", name: { en: "IT Support", ar: "دعم تقني" } },
      { slug: "cybersecurity", iconId: "security", name: { en: "Cybersecurity", ar: "أمن سيبراني" } },
      { slug: "hosting-domains", iconId: "globe", name: { en: "Hosting & Domains", ar: "استضافة ونطاقات" } },
      { slug: "ecommerce", iconId: "shopping", name: { en: "E-commerce", ar: "تجارة إلكترونية" } },
    ],
  },
  {
    slug: "marketing-media",
    iconId: "marketing",
    name: { en: "Marketing & Media", ar: "التسويق والإعلام" },
    children: [
      { slug: "digital-marketing", iconId: "marketing", name: { en: "Digital Marketing", ar: "تسويق رقمي" } },
      { slug: "branding", iconId: "art", name: { en: "Branding", ar: "هوية بصرية" } },
      { slug: "photography", iconId: "photo", name: { en: "Photography", ar: "تصوير" } },
      { slug: "videography", iconId: "video", name: { en: "Videography", ar: "تصوير فيديو" } },
      { slug: "printing-signage", iconId: "printing", name: { en: "Printing & Signage", ar: "طباعة ولوحات" } },
      { slug: "social-media", iconId: "notifications", name: { en: "Social Media", ar: "وسائل التواصل" } },
    ],
  },
  {
    slug: "automotive-transport",
    iconId: "auto",
    name: { en: "Automotive & Transport", ar: "السيارات والنقل" },
    children: [
      { slug: "car-repair", iconId: "repair", name: { en: "Car Repair", ar: "صيانة سيارات" } },
      { slug: "car-wash", iconId: "droplet", name: { en: "Car Wash", ar: "غسيل سيارات" } },
      { slug: "car-rental", iconId: "transport", name: { en: "Car Rental", ar: "تأجير سيارات" } },
      { slug: "towing", iconId: "truck", name: { en: "Towing", ar: "سحب" } },
      { slug: "auto-parts", iconId: "hardware", name: { en: "Auto Parts", ar: "قطع غيار" } },
      { slug: "transport-services", iconId: "transport", name: { en: "Transport Services", ar: "خدمات نقل" } },
    ],
  },
  {
    slug: "home-construction",
    iconId: "home-services",
    name: { en: "Home & Construction", ar: "المنزل والإنشاءات" },
    children: [
      { slug: "plumbing", iconId: "repair", name: { en: "Plumbing", ar: "سباكة" } },
      { slug: "electricians", iconId: "energy", name: { en: "Electrical", ar: "كهرباء" } },
      { slug: "ac-hvac", iconId: "repair", name: { en: "AC & HVAC", ar: "تكييف وتبريد" } },
      { slug: "cleaning-services", iconId: "home-services", name: { en: "Cleaning Services", ar: "خدمات تنظيف" } },
      { slug: "construction-contractors", iconId: "construction", name: { en: "Contractors", ar: "مقاولات" } },
      { slug: "interior-design", iconId: "art", name: { en: "Interior Design", ar: "تصميم داخلي" } },
      { slug: "building-materials", iconId: "construction", name: { en: "Building Materials", ar: "مواد بناء" } },
      { slug: "landscaping", iconId: "home-services", name: { en: "Landscaping", ar: "تنسيق حدائق" } },
    ],
  },
  {
    slug: "real-estate",
    iconId: "real-estate",
    name: { en: "Real Estate", ar: "العقارات" },
    children: [
      { slug: "real-estate-agencies", iconId: "real-estate", name: { en: "Agencies", ar: "مكاتب عقار" } },
      { slug: "property-management", iconId: "real-estate", name: { en: "Property Management", ar: "إدارة أملاك" } },
      { slug: "short-term-rentals", iconId: "hotel", name: { en: "Short-term Rentals", ar: "إيجارات قصيرة" } },
    ],
  },
  {
    slug: "travel-tourism",
    iconId: "travel",
    name: { en: "Travel & Tourism", ar: "السفر والسياحة" },
    children: [
      { slug: "travel-agencies", iconId: "travel", name: { en: "Travel Agencies", ar: "وكالات سفر" } },
      { slug: "tour-guides", iconId: "location", name: { en: "Tour Guides", ar: "مرشدون سياحيون" } },
      { slug: "hotels", iconId: "hotel", name: { en: "Hotels", ar: "فنادق" } },
      { slug: "car-hire", iconId: "transport", name: { en: "Car Hire", ar: "تأجير" } },
    ],
  },
  {
    slug: "finance-insurance",
    iconId: "finance",
    name: { en: "Finance & Insurance", ar: "المالية والتأمين" },
    children: [
      { slug: "banks", iconId: "finance", name: { en: "Banks", ar: "بنوك" } },
      { slug: "money-exchange", iconId: "finance", name: { en: "Money Exchange", ar: "صرافة" } },
      { slug: "insurance", iconId: "umbrella", name: { en: "Insurance", ar: "تأمين" } },
      { slug: "fintech", iconId: "stats", name: { en: "Fintech", ar: "تقنية مالية" } },
    ],
  },
  {
    slug: "manufacturing-industry",
    iconId: "manufacturing",
    name: { en: "Manufacturing & Industry", ar: "التصنيع والصناعة" },
    children: [
      { slug: "factories", iconId: "manufacturing", name: { en: "Factories", ar: "مصانع" } },
      { slug: "packaging", iconId: "package", name: { en: "Packaging", ar: "تعبئة وتغليف" } },
      { slug: "workshops", iconId: "repair", name: { en: "Workshops", ar: "ورش" } },
    ],
  },
  {
    slug: "logistics-warehousing",
    iconId: "logistics",
    name: { en: "Logistics & Warehousing", ar: "اللوجستيات والتخزين" },
    children: [
      { slug: "courier", iconId: "delivery", name: { en: "Courier Services", ar: "شحن سريع" } },
      { slug: "freight", iconId: "truck", name: { en: "Freight", ar: "شحن" } },
      { slug: "warehousing", iconId: "archive", name: { en: "Warehousing", ar: "مستودعات" } },
    ],
  },
  {
    slug: "agriculture-food-production",
    iconId: "agriculture",
    name: { en: "Agriculture & Food Production", ar: "الزراعة والإنتاج الغذائي" },
    children: [
      { slug: "farms", iconId: "agriculture", name: { en: "Farms", ar: "مزارع" } },
      { slug: "fisheries", iconId: "agriculture", name: { en: "Fisheries", ar: "صيد وأسماك" } },
      { slug: "food-processing", iconId: "manufacturing", name: { en: "Food Processing", ar: "تصنيع غذائي" } },
    ],
  },
  {
    slug: "pets-animals",
    iconId: "pets",
    name: { en: "Pets & Animals", ar: "الحيوانات الأليفة" },
    children: [
      { slug: "veterinary", iconId: "healthcare", name: { en: "Veterinary", ar: "بيطري" } },
      { slug: "pet-shops", iconId: "pets", name: { en: "Pet Shops", ar: "محلات حيوانات" } },
      { slug: "pet-grooming", iconId: "beauty", name: { en: "Pet Grooming", ar: "تجميل حيوانات" } },
    ],
  },
  {
    slug: "events-entertainment",
    iconId: "events",
    name: { en: "Events & Entertainment", ar: "الفعاليات والترفيه" },
    children: [
      { slug: "event-planners", iconId: "events", name: { en: "Event Planning", ar: "تنظيم فعاليات" } },
      { slug: "wedding-services", iconId: "gift", name: { en: "Wedding Services", ar: "خدمات زفاف" } },
      { slug: "venues", iconId: "location", name: { en: "Venues", ar: "قاعات" } },
      { slug: "kids-entertainment", iconId: "kids", name: { en: "Kids Entertainment", ar: "ترفيه أطفال" } },
    ],
  },
  {
    slug: "sports-recreation",
    iconId: "fitness",
    name: { en: "Sports & Recreation", ar: "الرياضة والترفيه" },
    children: [
      { slug: "sports-clubs", iconId: "fitness", name: { en: "Sports Clubs", ar: "نوادي رياضية" } },
      { slug: "swimming", iconId: "fitness", name: { en: "Swimming", ar: "سباحة" } },
      { slug: "outdoor-activities", iconId: "travel", name: { en: "Outdoor Activities", ar: "أنشطة خارجية" } },
    ],
  },
  {
    slug: "nonprofit-community",
    iconId: "nonprofit",
    name: { en: "Nonprofit & Community", ar: "غير ربحي ومجتمع" },
    children: [
      { slug: "charities", iconId: "nonprofit", name: { en: "Charities", ar: "جمعيات خيرية" } },
      { slug: "community-centers", iconId: "users", name: { en: "Community Centers", ar: "مراكز مجتمعية" } },
    ],
  },
];
